package com.yunzhong.datat.application.model;

import java.io.Serializable;

public class JobContent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_content.job_content_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private Long jobContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_content.job_name
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_content.job_content
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private String jobContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_content
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_content.job_content_id
     *
     * @return the value of job_content.job_content_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public Long getJobContentId() {
        return jobContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_content.job_content_id
     *
     * @param jobContentId the value for job_content.job_content_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setJobContentId(Long jobContentId) {
        this.jobContentId = jobContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_content.job_name
     *
     * @return the value of job_content.job_name
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_content.job_name
     *
     * @param jobName the value for job_content.job_name
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_content.job_content
     *
     * @return the value of job_content.job_content
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public String getJobContent() {
        return jobContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_content.job_content
     *
     * @param jobContent the value for job_content.job_content
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setJobContent(String jobContent) {
        this.jobContent = jobContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobContentId=").append(jobContentId);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobContent=").append(jobContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}