package com.yunzhong.datat.application.model;

import java.util.ArrayList;
import java.util.List;

public class JobCommunicationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public JobCommunicationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInstanceIdIsNull() {
            addCriterion("instance_id is null");
            return (Criteria) this;
        }

        public Criteria andInstanceIdIsNotNull() {
            addCriterion("instance_id is not null");
            return (Criteria) this;
        }

        public Criteria andInstanceIdEqualTo(Long value) {
            addCriterion("instance_id =", value, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdNotEqualTo(Long value) {
            addCriterion("instance_id <>", value, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdGreaterThan(Long value) {
            addCriterion("instance_id >", value, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("instance_id >=", value, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdLessThan(Long value) {
            addCriterion("instance_id <", value, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdLessThanOrEqualTo(Long value) {
            addCriterion("instance_id <=", value, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdIn(List<Long> values) {
            addCriterion("instance_id in", values, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdNotIn(List<Long> values) {
            addCriterion("instance_id not in", values, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdBetween(Long value1, Long value2) {
            addCriterion("instance_id between", value1, value2, "instanceId");
            return (Criteria) this;
        }

        public Criteria andInstanceIdNotBetween(Long value1, Long value2) {
            addCriterion("instance_id not between", value1, value2, "instanceId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdIsNull() {
            addCriterion("job_content_id is null");
            return (Criteria) this;
        }

        public Criteria andJobContentIdIsNotNull() {
            addCriterion("job_content_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobContentIdEqualTo(Long value) {
            addCriterion("job_content_id =", value, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdNotEqualTo(Long value) {
            addCriterion("job_content_id <>", value, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdGreaterThan(Long value) {
            addCriterion("job_content_id >", value, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("job_content_id >=", value, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdLessThan(Long value) {
            addCriterion("job_content_id <", value, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdLessThanOrEqualTo(Long value) {
            addCriterion("job_content_id <=", value, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdIn(List<Long> values) {
            addCriterion("job_content_id in", values, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdNotIn(List<Long> values) {
            addCriterion("job_content_id not in", values, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdBetween(Long value1, Long value2) {
            addCriterion("job_content_id between", value1, value2, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobContentIdNotBetween(Long value1, Long value2) {
            addCriterion("job_content_id not between", value1, value2, "jobContentId");
            return (Criteria) this;
        }

        public Criteria andJobStateIsNull() {
            addCriterion("job_state is null");
            return (Criteria) this;
        }

        public Criteria andJobStateIsNotNull() {
            addCriterion("job_state is not null");
            return (Criteria) this;
        }

        public Criteria andJobStateEqualTo(String value) {
            addCriterion("job_state =", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateNotEqualTo(String value) {
            addCriterion("job_state <>", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateGreaterThan(String value) {
            addCriterion("job_state >", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateGreaterThanOrEqualTo(String value) {
            addCriterion("job_state >=", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateLessThan(String value) {
            addCriterion("job_state <", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateLessThanOrEqualTo(String value) {
            addCriterion("job_state <=", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateLike(String value) {
            addCriterion("job_state like", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateNotLike(String value) {
            addCriterion("job_state not like", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateIn(List<String> values) {
            addCriterion("job_state in", values, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateNotIn(List<String> values) {
            addCriterion("job_state not in", values, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateBetween(String value1, String value2) {
            addCriterion("job_state between", value1, value2, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateNotBetween(String value1, String value2) {
            addCriterion("job_state not between", value1, value2, "jobState");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Long value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Long value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Long value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Long value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Long value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Long value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Long> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Long> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Long value1, Long value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Long value1, Long value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_communication
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 30 08:52:13 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}