package com.yunzhong.datat.application.model;

import java.io.Serializable;

public class JobCommunication implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_communication.instance_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private Long instanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_communication.job_content_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private Long jobContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_communication.job_state
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private String jobState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_communication.timestamp
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private Long timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_communication.counter
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private String counter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_communication.message
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_communication.instance_id
     *
     * @return the value of job_communication.instance_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public Long getInstanceId() {
        return instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_communication.instance_id
     *
     * @param instanceId the value for job_communication.instance_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setInstanceId(Long instanceId) {
        this.instanceId = instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_communication.job_content_id
     *
     * @return the value of job_communication.job_content_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public Long getJobContentId() {
        return jobContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_communication.job_content_id
     *
     * @param jobContentId the value for job_communication.job_content_id
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setJobContentId(Long jobContentId) {
        this.jobContentId = jobContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_communication.job_state
     *
     * @return the value of job_communication.job_state
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public String getJobState() {
        return jobState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_communication.job_state
     *
     * @param jobState the value for job_communication.job_state
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setJobState(String jobState) {
        this.jobState = jobState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_communication.timestamp
     *
     * @return the value of job_communication.timestamp
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_communication.timestamp
     *
     * @param timestamp the value for job_communication.timestamp
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_communication.counter
     *
     * @return the value of job_communication.counter
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public String getCounter() {
        return counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_communication.counter
     *
     * @param counter the value for job_communication.counter
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setCounter(String counter) {
        this.counter = counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_communication.message
     *
     * @return the value of job_communication.message
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_communication.message
     *
     * @param message the value for job_communication.message
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", instanceId=").append(instanceId);
        sb.append(", jobContentId=").append(jobContentId);
        sb.append(", jobState=").append(jobState);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", counter=").append(counter);
        sb.append(", message=").append(message);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}