package com.yunzhong.datat.application.model;

import java.io.Serializable;

public class JobInstance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_instance.id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_instance.job_content_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private Long jobContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_instance.start_timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private Long startTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_instance.end_timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private Long endTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_instance.state
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_instance.server_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private String serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_instance
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_instance.id
     *
     * @return the value of job_instance.id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_instance.id
     *
     * @param id the value for job_instance.id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_instance.job_content_id
     *
     * @return the value of job_instance.job_content_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Long getJobContentId() {
        return jobContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_instance.job_content_id
     *
     * @param jobContentId the value for job_instance.job_content_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setJobContentId(Long jobContentId) {
        this.jobContentId = jobContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_instance.start_timestamp
     *
     * @return the value of job_instance.start_timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Long getStartTimestamp() {
        return startTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_instance.start_timestamp
     *
     * @param startTimestamp the value for job_instance.start_timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setStartTimestamp(Long startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_instance.end_timestamp
     *
     * @return the value of job_instance.end_timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Long getEndTimestamp() {
        return endTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_instance.end_timestamp
     *
     * @param endTimestamp the value for job_instance.end_timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setEndTimestamp(Long endTimestamp) {
        this.endTimestamp = endTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_instance.state
     *
     * @return the value of job_instance.state
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_instance.state
     *
     * @param state the value for job_instance.state
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_instance.server_id
     *
     * @return the value of job_instance.server_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_instance.server_id
     *
     * @param serverId the value for job_instance.server_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", jobContentId=").append(jobContentId);
        sb.append(", startTimestamp=").append(startTimestamp);
        sb.append(", endTimestamp=").append(endTimestamp);
        sb.append(", state=").append(state);
        sb.append(", serverId=").append(serverId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}