package com.yunzhong.datat.application.model;

import java.io.Serializable;

public class TgCommunication implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_communication.job_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_communication.tg_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private Integer tgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_communication.tg_state
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private String tgState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_communication.timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private Long timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_communication.tg_message
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private String tgMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_communication.tg_counter
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private String tgCounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_communication.job_id
     *
     * @return the value of tg_communication.job_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_communication.job_id
     *
     * @param jobId the value for tg_communication.job_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_communication.tg_id
     *
     * @return the value of tg_communication.tg_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Integer getTgId() {
        return tgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_communication.tg_id
     *
     * @param tgId the value for tg_communication.tg_id
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setTgId(Integer tgId) {
        this.tgId = tgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_communication.tg_state
     *
     * @return the value of tg_communication.tg_state
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public String getTgState() {
        return tgState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_communication.tg_state
     *
     * @param tgState the value for tg_communication.tg_state
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setTgState(String tgState) {
        this.tgState = tgState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_communication.timestamp
     *
     * @return the value of tg_communication.timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_communication.timestamp
     *
     * @param timestamp the value for tg_communication.timestamp
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_communication.tg_message
     *
     * @return the value of tg_communication.tg_message
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public String getTgMessage() {
        return tgMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_communication.tg_message
     *
     * @param tgMessage the value for tg_communication.tg_message
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setTgMessage(String tgMessage) {
        this.tgMessage = tgMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_communication.tg_counter
     *
     * @return the value of tg_communication.tg_counter
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public String getTgCounter() {
        return tgCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_communication.tg_counter
     *
     * @param tgCounter the value for tg_communication.tg_counter
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setTgCounter(String tgCounter) {
        this.tgCounter = tgCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobId=").append(jobId);
        sb.append(", tgId=").append(tgId);
        sb.append(", tgState=").append(tgState);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", tgMessage=").append(tgMessage);
        sb.append(", tgCounter=").append(tgCounter);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}