package com.yunzhong.datat.application.model;

import java.util.ArrayList;
import java.util.List;

public class TgCommunicationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public TgCommunicationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobIdIsNull() {
            addCriterion("job_id is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("job_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(Long value) {
            addCriterion("job_id =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(Long value) {
            addCriterion("job_id <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(Long value) {
            addCriterion("job_id >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(Long value) {
            addCriterion("job_id >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(Long value) {
            addCriterion("job_id <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(Long value) {
            addCriterion("job_id <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<Long> values) {
            addCriterion("job_id in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<Long> values) {
            addCriterion("job_id not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(Long value1, Long value2) {
            addCriterion("job_id between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(Long value1, Long value2) {
            addCriterion("job_id not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andTgIdIsNull() {
            addCriterion("tg_id is null");
            return (Criteria) this;
        }

        public Criteria andTgIdIsNotNull() {
            addCriterion("tg_id is not null");
            return (Criteria) this;
        }

        public Criteria andTgIdEqualTo(Integer value) {
            addCriterion("tg_id =", value, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdNotEqualTo(Integer value) {
            addCriterion("tg_id <>", value, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdGreaterThan(Integer value) {
            addCriterion("tg_id >", value, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tg_id >=", value, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdLessThan(Integer value) {
            addCriterion("tg_id <", value, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdLessThanOrEqualTo(Integer value) {
            addCriterion("tg_id <=", value, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdIn(List<Integer> values) {
            addCriterion("tg_id in", values, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdNotIn(List<Integer> values) {
            addCriterion("tg_id not in", values, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdBetween(Integer value1, Integer value2) {
            addCriterion("tg_id between", value1, value2, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tg_id not between", value1, value2, "tgId");
            return (Criteria) this;
        }

        public Criteria andTgStateIsNull() {
            addCriterion("tg_state is null");
            return (Criteria) this;
        }

        public Criteria andTgStateIsNotNull() {
            addCriterion("tg_state is not null");
            return (Criteria) this;
        }

        public Criteria andTgStateEqualTo(String value) {
            addCriterion("tg_state =", value, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateNotEqualTo(String value) {
            addCriterion("tg_state <>", value, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateGreaterThan(String value) {
            addCriterion("tg_state >", value, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateGreaterThanOrEqualTo(String value) {
            addCriterion("tg_state >=", value, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateLessThan(String value) {
            addCriterion("tg_state <", value, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateLessThanOrEqualTo(String value) {
            addCriterion("tg_state <=", value, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateLike(String value) {
            addCriterion("tg_state like", value, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateNotLike(String value) {
            addCriterion("tg_state not like", value, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateIn(List<String> values) {
            addCriterion("tg_state in", values, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateNotIn(List<String> values) {
            addCriterion("tg_state not in", values, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateBetween(String value1, String value2) {
            addCriterion("tg_state between", value1, value2, "tgState");
            return (Criteria) this;
        }

        public Criteria andTgStateNotBetween(String value1, String value2) {
            addCriterion("tg_state not between", value1, value2, "tgState");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Long value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Long value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Long value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Long value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Long value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Long value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Long> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Long> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Long value1, Long value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Long value1, Long value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tg_communication
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 24 21:05:29 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tg_communication
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}