package com.yunzhong.datat.application.mapper;

import com.yunzhong.datat.application.model.JobContent;
import com.yunzhong.datat.application.model.JobContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    long countByExample(JobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int deleteByExample(JobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int deleteByPrimaryKey(Long jobContentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int insert(JobContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int insertSelective(JobContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    List<JobContent> selectByExampleWithBLOBs(JobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    List<JobContent> selectByExample(JobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    JobContent selectByPrimaryKey(Long jobContentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int updateByExampleSelective(@Param("row") JobContent row, @Param("example") JobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") JobContent row, @Param("example") JobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int updateByExample(@Param("row") JobContent row, @Param("example") JobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int updateByPrimaryKeySelective(JobContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(JobContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_content
     *
     * @mbg.generated Wed Aug 24 21:05:29 CST 2022
     */
    int updateByPrimaryKey(JobContent row);
}