package com.yunzhong.datat.application.mapper;

import com.yunzhong.datat.application.model.JobCommunication;
import com.yunzhong.datat.application.model.JobCommunicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobCommunicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    long countByExample(JobCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int deleteByExample(JobCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int insert(JobCommunication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int insertSelective(JobCommunication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    List<JobCommunication> selectByExampleWithBLOBs(JobCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    List<JobCommunication> selectByExample(JobCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int updateByExampleSelective(@Param("row") JobCommunication row, @Param("example") JobCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") JobCommunication row, @Param("example") JobCommunicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_communication
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int updateByExample(@Param("row") JobCommunication row, @Param("example") JobCommunicationExample example);
}