package com.yunzhong.datat.application.mapper;

import com.yunzhong.datat.application.model.JobInstance;
import com.yunzhong.datat.application.model.JobInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    long countByExample(JobInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int deleteByExample(JobInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int insert(JobInstance row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int insertSelective(JobInstance row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    List<JobInstance> selectByExample(JobInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    JobInstance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int updateByExampleSelective(@Param("row") JobInstance row, @Param("example") JobInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int updateByExample(@Param("row") JobInstance row, @Param("example") JobInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int updateByPrimaryKeySelective(JobInstance row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_instance
     *
     * @mbg.generated Fri Sep 30 08:52:13 CST 2022
     */
    int updateByPrimaryKey(JobInstance row);
}